# Triggers
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  # Build Job
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install NPM Dependencies
        working-directory: ./
        run: npm i
      - name: Build Project
        working-directory: ./
        run: npm run build --prod
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./frontend/dist/apps/frontend
  # Deploy Job
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist/apps/frontend
      - name: Deploy to gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/frontend